name: CONSENSO_D
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - expect
  - minimap2=2.26
  - samtools=1.19.2
  - bcftools=1.19
  - perl
  - seqtk=1.4
  - mafft
  - raxml
  - mariadb-connector-c
  - mariadb
  - tk
  - pip
  - matplotlib
  - pandas
  - numpy
  - seaborn
  - pip:
      - pillow
      - nextstrain-cli
