name: CONSENSO_D
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - expect
  - minimap2=2.26
  - bwa
  - samtools=1.19.2
  - bcftools=1.19
  - perl
  - seqtk=1.4
  - mafft
  - raxml
  - mariadb-connector-c
  - mariadb
  - tk
  - pip
  - matplotlib
  - pandas
  - numpy
  - seaborn
  - fastqc
  - multiqc
  - spades
  - joblib=1.4.2
  - scikit-learn=1.3.2
  - cyvcf2
  - trimmomatic
  - cutadapt
  - gnuplot
  - biopython
  - plotly
  - pip:
      - pillow
      - nextstrain-cli
